### ISSUE TITLE
env files don't specify PSQL variables

### ISSUE THREAD

**Issue by dheerajchand** [siege-analytics/geodjango_simple_template#5]
env variables required for `postgis` image aren't in any env file.

```
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_HOST_AUTH_METHOD
```

Suggested refactor is to have 

1. one base env file that has common variables for all environments
2. specific files for environments (dev/prod) 
3. make command to cat/overwrite base file with the specific file in each case as necessary

**Comment by caracolmzd** [comment]
Yeah, I like discrete env files. 
I'll see about using just a little bit of the approach I did in socialwarehouse without expanding the scope of this ticket.
